language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: JK3hDXRDo7IIbxh18vMQcXQB9kMEkHOdknXPIuQcg3TYMhN92p0Dp9UmhQbsLtWHSxzkWskgpf3wqUFYAhq372reMD1x2cpF3G88e9neJwqBVAUrCCLVYoX7U6dPUs8usprYXbpSt+EaRNtlY25XShIv5ruXB0As6t0vsgN1rqg=
  - secure: feEQrs6jnG9hUqP4hZ47wF17IBTtv4pyyUjr2dnnjvUvEPl0OBMgwv2u8DSHAdRzRu6VCMVMUWMzeS3KFQ6wImMrAJGc4QAlz8cXyM2vT4lVYFxuflUJR0tTbB0yI4F/siwscPV1586Lv1/ZJwiq/VarOaqWjvI+BJWrB2apmhU=
  - secure: B+BrXkCAftN3YxkDVinCCNT4vrw9V7oPFczNB2Y/PztSQzLEApjR34nIHazRGOa5qC4351M62gL5LlGlruaj/lKEloFCX9xia0eFhkssAwfo+mEtVk8DGGW+MvL1HYCyJmcCfBbA/r3AoPGiPGYGYOLVmIqxd1w54dB3mytsgkE=
