language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: Dx2pqzulcauIhVXEqQoNbnwm/EZzam9smHyBd1sPHnnOt5OgikYqnZ5dJOq8gh9wCRCHt1c64NSW0g/04VDofqpBGFifL4eO/c1ZtDioTG4LT+aPXLkt0S7VXP0r2J29JyvcVMBgTi3WRQdBDk4Pd1kYgQlASGSctQmK+Cqw3Jc=
  - secure: K8Uy8SoQN8S9WuFbeZFBID6XLa7ecgzzB6HoETk91BYJccXTv+VrccnbQ6XYO2cFa5aZyL7QnQjzMRfhjofypr1jvOjVoegfulUGhveypUzEQ1ylnCA8V0bBPHuvMN76ut5fJuUfD49j5dcFjtrdiollZVUiVW1TKjzpJKA4fi0=
  - secure: dpj8ThIN7WHFqis/Sy3K2eyI34gjzAyqQcsLy1uz5fM46reSJ6/TMurl12jgPLNototlox6T+HxLTmegu4j3O7JmUeQDAR4S+2nwPbvZmC/s8APKPca5fOEJ2iW8Fyp5MKC13fUjvq+qm/CCr8o0Dmz3QdjIdftDxBsspUGlpEA=
