// Generated by CoffeeScript 1.10.0
(function() {
  var imgflo, main, minimist;

  imgflo = require('./imgflo-url');

  minimist = require('minimist');

  main = function() {
    var config, e, error, graphname, k, params, parsed, url, v;
    parsed = minimist(process.argv.slice(2));
    config = {
      key: process.env.IMGFLO_API_KEY,
      secret: process.env.IMGFLO_API_SECRET,
      server: 'https://imgflo.herokuapp.com/'
    };
    if (process.env.IMGFLO_API_SERVER != null) {
      config.server = process.env.IMGFLO_API_SERVER;
    }
    for (k in config) {
      v = config[k];
      if (!v) {
        config[k] = null;
      }
    }
    graphname = parsed._[0];
    params = {};
    for (k in parsed) {
      v = parsed[k];
      if (k === '_') {
        continue;
      }
      params[k] = v;
    }
    try {
      url = imgflo(config, graphname, params);
    } catch (error) {
      e = error;
      process.stderr.write("ERROR: " + e.message + "\n");
      process.exit(1);
    }
    return process.stdout.write(url);
  };

  exports.main = main;

}).call(this);
